CREATE TABLE [dbo].[severityRatings] (
    [id]       INT            IDENTITY (1, 1) NOT NULL,
    [VirusId]  NVARCHAR (MAX) NULL,
    [Saved]    BIT            NOT NULL,
    [coverage] BIT            NOT NULL,
    [nickName] NVARCHAR (MAX) NULL,
    [userName] NVARCHAR (MAX) NULL,
    [iR]       NVARCHAR (MAX) NULL,
    [iA]       NVARCHAR (MAX) NULL,
    [iE]       NVARCHAR (MAX) NULL,
    [iL]       NVARCHAR (MAX) NULL,
    [iF]       NVARCHAR (MAX) NULL,
    [iC]       NVARCHAR (MAX) NULL,
    [iP]       NVARCHAR (MAX) NULL,
    [iO]       NVARCHAR (MAX) NULL,
    [cR]       NVARCHAR (MAX) NULL,
    [cA]       NVARCHAR (MAX) NULL,
    [cE]       NVARCHAR (MAX) NULL,
    [cL]       NVARCHAR (MAX) NULL,
    [cF]       NVARCHAR (MAX) NULL,
    [cC]       NVARCHAR (MAX) NULL,
    [cP]       NVARCHAR (MAX) NULL,
    [cO]       NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_dbo.severityRatings] PRIMARY KEY CLUSTERED ([id] ASC)
);

